// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5Vkowkn-xEUmdAj6eIKuNHb4s1yA2BT0',
    appId: '1:204057412893:web:e6d21e6d3231bd0faccdf4',
    messagingSenderId: '204057412893',
    projectId: 'freelancer2capitalist-59630',
    authDomain: 'freelancer2capitalist-59630.firebaseapp.com',
    storageBucket: 'freelancer2capitalist-59630.appspot.com',
    measurementId: 'G-H29P9KC0WC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCns2tVlP2Txe96FnI1DY6NYOrGhwNMjrc',
    appId: '1:204057412893:android:795f22e5b59e3d88accdf4',
    messagingSenderId: '204057412893',
    projectId: 'freelancer2capitalist-59630',
    storageBucket: 'freelancer2capitalist-59630.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOdcUu2x2wjraSxE6wmbGu6la7XCAklVs',
    appId: '1:204057412893:ios:ede071ed2cc12cafaccdf4',
    messagingSenderId: '204057412893',
    projectId: 'freelancer2capitalist-59630',
    storageBucket: 'freelancer2capitalist-59630.appspot.com',
    iosClientId: '204057412893-ihsn6h7rt2t8qke3e5h2enque40lm4eq.apps.googleusercontent.com',
    iosBundleId: 'com.example.freelancer2capitalist',
  );
}
